<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("test");
//$APPLICATION->AddHeadScript('http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.js');
//$APPLICATION->AddHeadScript('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js');

?><?$APPLICATION->IncludeComponent(
	"api:reviews", 
	".default", 
	array(
		"CACHE_TIME" => "31536000",
		"CACHE_TYPE" => "N",
		"COLOR" => "turquoise",
		"COMPONENT_TEMPLATE" => ".default",
		"DETAIL_HASH" => "",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_ID" => "375",
		"EMAIL_TO" => "",
		"FORM_CITY_VIEW" => "Y",
		"FORM_DELIVERY" => array(
		),
		"FORM_DISPLAY_FIELDS" => array(
			0 => "RATING",
			1 => "TITLE",
			2 => "ADVANTAGE",
			3 => "DISADVANTAGE",
			4 => "ANNOTATION",
			5 => "GUEST_NAME",
			6 => "GUEST_EMAIL",
		),
		"FORM_FORM_SUBTITLE" => "",
		"FORM_FORM_TITLE" => "Отзыв о товаре",
		"FORM_MESS_ADD_REVIEW_ERROR" => "Внимание!<br>Ошибка добавления отзыва",
		"FORM_MESS_ADD_REVIEW_EVENT_TEXT" => "<p>#USER_NAME# добавил(а) новый отзыв (оценка: #RATING#) ##ID#</p>
<p>Открыть в админке #LINK_ADMIN#</p>
<p>Открыть на сайте #LINK#</p>",
		"FORM_MESS_ADD_REVIEW_EVENT_THEME" => "Отзыв о товаре (оценка: #RATING#) ##ID#",
		"FORM_MESS_ADD_REVIEW_MODERATION" => "Спасибо!<br>Ваш отзыв отправлен на модерацию",
		"FORM_MESS_ADD_REVIEW_VIZIBLE" => "Спасибо!<br>Ваш отзыв №#ID# опубликован",
		"FORM_MESS_EULA" => "Нажимая кнопку «Отправить отзыв», я принимаю условия Пользовательского соглашения и даю своё согласие на обработку моих персональных данных, в соответствии с Федеральным законом от 27.07.2006 года №152-ФЗ «О персональных данных», на условиях и для целей, определенных Политикой конфиденциальности.",
		"FORM_MESS_EULA_CONFIRM" => "Для продолжения вы должны принять условия Пользовательского соглашения",
		"FORM_MESS_FIELD_PLACEHOLDER_ADVANTAGE" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_ANNOTATION" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_CITY" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_COMPANY" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_DELIVERY" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_DISADVANTAGE" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_FILES" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_GUEST_EMAIL" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_GUEST_NAME" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_GUEST_PHONE" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_ORDER_ID" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_RATING" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_TITLE" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_VIDEOS" => "",
		"FORM_MESS_FIELD_PLACEHOLDER_WEBSITE" => "",
		"FORM_MESS_PRIVACY" => "Я согласен на обработку персональных данных",
		"FORM_MESS_PRIVACY_CONFIRM" => "Для продолжения вы должны принять соглашение на обработку персональных данных",
		"FORM_MESS_PRIVACY_LINK" => "",
		"FORM_MESS_STAR_RATING_1" => "Ужасный товар",
		"FORM_MESS_STAR_RATING_2" => "Плохой товар",
		"FORM_MESS_STAR_RATING_3" => "Обычный товар",
		"FORM_MESS_STAR_RATING_4" => "Хороший товар",
		"FORM_MESS_STAR_RATING_5" => "Отличный товар",
		"FORM_PREMODERATION" => "A",
		"FORM_REQUIRED_FIELDS" => array(
			0 => "RATING",
			1 => "TITLE",
			2 => "ANNOTATION",
		),
		"FORM_RULES_LINK" => "http://1167340.casualua.web.hosting-test.net/rules/",
		"FORM_RULES_TEXT" => "Правила публикации отзывов",
		"FORM_SHOP_BTN_TEXT" => "Оставить свой отзыв",
		"FORM_SHOP_TEXT" => "Отзывы о товаре",
		"FORM_USE_EULA" => "N",
		"FORM_USE_PRIVACY" => "N",
		"IBLOCK_ID" => "4",
		"INCLUDE_CSS" => "Y",
		"INCLUDE_JQUERY" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_ITEMS_LIMIT" => "10",
		"LIST_MESS_ADD_UNSWER_EVENT_TEXT" => "#USER_NAME#, здравствуйте! 
К Вашему отзыву добавлен официальный ответ, для просмотра перейдите по ссылке #LINK#",
		"LIST_MESS_ADD_UNSWER_EVENT_THEME" => "Официальный ответ к вашему отзыву",
		"LIST_MESS_HELPFUL_REVIEW" => "Отзыв полезен?",
		"LIST_MESS_TRUE_BUYER" => "Проверенный покупатель",
		"LIST_SET_TITLE" => "N",
		"LIST_SHOP_NAME_REPLY" => "товар",
		"LIST_SHOW_THUMBS" => "Y",
		"LIST_SORT_FIELDS" => array(
		),
		"LIST_SORT_FIELD_1" => "ACTIVE_FROM",
		"LIST_SORT_FIELD_2" => "DATE_CREATE",
		"LIST_SORT_FIELD_3" => "ID",
		"LIST_SORT_ORDER_1" => "DESC",
		"LIST_SORT_ORDER_2" => "DESC",
		"LIST_SORT_ORDER_3" => "DESC",
		"MESSAGE_404" => "",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "31536000",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_THEME" => "green",
		"PAGER_TITLE" => "Отзывы",
		"PICTURE" => array(
		),
		"RESIZE_PICTURE" => "48x48",
		"SECTION_ID" => "16",
		"SEF_MODE" => "N",
		"SET_STATUS_404" => "N",
		"SHOP_NAME" => "",
		"SHOW_404" => "N",
		"STAT_MESS_CUSTOMER_RATING" => "На основе #N# оценок покупателей",
		"STAT_MESS_CUSTOMER_REVIEWS" => "Отзывы покупателей <span class=\"api-reviews-count\"></span>",
		"STAT_MESS_TOTAL_RATING" => "Рейтинг покупателей",
		"STAT_MIN_AVERAGE_RATING" => "5",
		"THEME" => "eshop",
		"THUMBNAIL_HEIGHT" => "72",
		"THUMBNAIL_WIDTH" => "114",
		"UPLOAD_FILE_LIMIT" => "8",
		"UPLOAD_FILE_SIZE" => "1M",
		"UPLOAD_FILE_TYPE" => "jpg, gif, bmp, png, jpeg",
		"UPLOAD_VIDEO_LIMIT" => "8",
		"URL" => "/ua/test.php",
		"USE_FORM_MESS_FIELD_PLACEHOLDER" => "N",
		"USE_MESS_FIELD_NAME" => "N",
		"USE_STAT" => "Y",
		"USE_SUBSCRIBE" => "N",
		"USE_USER" => "Y",
		"VARIABLE_ALIASES" => array(
			"review_id" => "review_id",
			"user_id" => "user_id",
		)
	),
	false
);?><br>
 <br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>